on: push
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Read a variable
              run: echo "My user_name value is ${{ secrets.USER }}"
            
            - name: Read a variable
              run: echo "My user_name value is ${{ secrets.PASSWORD }}"
