name: continuous-integration-<nombre_alumno>

on:
    push:
        branches:
        - master

jobs:
    first-job:
        name: Create file with secrets
        runs-on: ubuntu-latest
    
        env:
            USERNAME: ${{ secrets.USER }}
            PASSWORD: ${{ secrets.PASSWORD }}

        steps:
          - name: Pruebas de SAST
            run: echo "Ejecución de pruebas de SAST"
            
          - name: Crear archivo de credenciales
            run: |
               sed "s/\${USERNAME}/$USERNAME/g; s/\${PASSWORD}/$PASSWORD/g" credentials.ini.tpl > credentials.ini
            
          - name: Build docker image
            run: |
                docker build -t devops_ws . --tag devops_ws_$(date +%s)