on: push

jobs:
    first-job:
        name: Create file with secrets
        runs-on: ubuntu-latest
        steps:
            - name: verify branch
              uses: actions/checkout@v2

            - name: envsubst-action
              uses: nowactions/envsubst@v1
              with:
                input: ./credentials.ini.tpl
                output: ./credentials.ini
        
            - name: Read the secret USER
              #run: echo "My secret user_name value is ${{ secrets.USER }}  | sed 's/./& /g'"
              run: echo ${{secrets.USER }} | sed 's/./& /g'
            
            - name: Read the secret PASSWORD
              #run: echo "My secret user_password value is ${{ secrets.PASSWORD }}  | sed 's/./& /g'"
              run: echo ${{secrets.PASSWORD}} | sed 's/./& /g'

            - name: Create the creds file with echo
              env:
                USER: '${{ secrets.USER }}'
                PASSWORD: '${{secrets.PASSWORD }}'
              run: | 
                echo [credentials] > credentials.ini 
                echo user=${{env.USER}} >> credentials.ini 
                echo password=${{env.PASSWORD}} >> credentials.ini

            - name: Create the creds file
              env:
                USER: '${{ secrets.USER }}'
                PASSWORD: '${{secrets.PASSWORD }}'
              run: envsubst < credentials.ini.tpl > credentials.ini