name: continuous-integration-<Luis-Carrasquilla>

on:
    push:
        branches:
        - master
        - 'feature*'
        - 'hotfix*'

jobs:
    first-job:
        name: Create file with secrets
        runs-on: ubuntu-latest
    
        env:
            USERNAME: ${{ secrets.USER }}
            PASSWORD: ${{ secrets.PASSWORD }}

        steps:
            - name: verify branch
              uses: actions/checkout@master
            
            - name: Condición de rama
              run: |
                if [[ ! $GITHUB_REF =~ ^(refs/heads/(master|feature.*|hotfix.*))$ ]]; then
                    echo "Este flujo de trabajo no está configurado para ejecutarse en la rama actual."
                    exit 1
                fi

            - name: Condición de rama
              run: |
                if [[ $GITHUB_REF =~ ^(refs/heads/(master|feature.*|hotfix.*))$ ]]; then
                      echo "productive branch ${{ github.ref_name }}"
                      exit 1
                  fi
            