name: pull-request-analysis-<Luis-Carrasquilla>
on:
  push:
    branches:
      - master
      - feature**
  pull_request:
    branches:
      - master
      - feature**
jobs:   
  analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar la rama actual
        uses: actions/checkout@v4
        with:
            sparse-checkout: .
        
      - name: Usando Github Token
        uses: ad-m/github-push-action@master
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Abrir un Pull Request - Update AUTHORS
        run: |
          git log --format='%aN <%aE>%n%cN <%cE>' | sort -u > AUTHORS
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: update authors
          title: Update AUTHORS
          body: Credit new contributors by updating AUTHORS
          branch: update-authors
      - name: Analizar el código
        run: |
            echo "Realizando análisis de SAST"
        
      - name: Comprobar cumplimiento de requisitos
        id: stepid
        run: |
          echo estamos en: ${{ github.repository }}
          if [ -f "allow_pull_request.txt" ]; then
            echo "El archivo 'allow_pull_request.txt' existe. Permitiendo Pull Request."
            echo "allow_pull=true" >> $GITHUB_OUTPUT
          else
            echo "El archivo 'allow_pull_request.txt' no existe. Impidiendo Pull Request."
            echo "allow_pull=false" >> $GITHUB_OUTPUT
          fi
      - name: Guardar allow_pull_request.txt como artefacto
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: allow_pull_request
          path: allow_pull_request.txt
  allow_build:
    runs-on: ubuntu-latest
    needs: analysis
    steps:
      - name: Permitir build si allow_pull es True
        if: ${{ steps.stepid.outputs.allow_pull }} == true
        run: echo "Permitiendo Pull Request"
  prevent_build:
    runs-on: ubuntu-latest
    needs: analysis
    steps:
      - name: Impedir build si allow_pull es False
        if: ${{ steps.stepid.outputs.allow_pull}} == false
        run: |
          echo "Build fallida. Impidiendo Pull Request"
          exit 1  

                        

                  