on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: verify branch
              uses: actions/checkout@v2

            - name: envsubst-action
              uses: danielr1996/envsubst-action@1.1.0
        
            - name: Read the secret USER
              #run: echo "My secret user_name value is ${{ secrets.USER }}  | sed 's/./& /g'"
              run: echo ${{secrets.USER }} | sed 's/./& /g'
            
            - name: Read the secret PASSWORD
              #run: echo "My secret user_password value is ${{ secrets.PASSWORD }}  | sed 's/./& /g'"
              run: echo ${{secrets.PASSWORD}} | sed 's/./& /g'

            - name: Create the creds file
              env:
                USER: '${{ secrets.USER }}'
                PASSWORD: '${{secrets.PASSWORD }}'
              run: envsubst < credentials.ini.tpl > credentials.ini