on: push
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Read the secret USER
              run: echo "My secret user_name value is ${{ secrets.USER }}"
            
            - name: Read the secret PASSWORD
              run: echo "My secret user_password value is ${{ secrets.PASSWORD }}"
